version: '2'
services:
  nats:
    # https://hub.docker.com/_/nats/
    image: nats
    ports:
    - 4222:4222
    - 8222:8222
    - 6222:6222

  listener:
    build:
      context: listener
      dockerfile: Dockerfile
    depends_on:
    - nats
    # https://github.com/Logimethods/docker-nats-connector-spark/blob/d1d83ebc4fc281250487ccb48751a536464021e8/compose/docker-compose.no-cluster.yml
    links:
    - nats
    environment:
    - NATS_URI=nats://nats:4222
